name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download NDK and unzip
      run: |
        # Set NDK version and download URL
        $NDK_VERSION = "r28"
        $NDK_URL = "https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-windows.zip?hl=th"
        
        # Download NDK ZIP
        Invoke-WebRequest -Uri $NDK_URL -OutFile "android-ndk.zip"

        # Unzip the NDK
        Expand-Archive -Path "android-ndk.zip" -DestinationPath "android-ndk"

    - name: Set up environment variables
      run: |
        $NDK_HOME = "$(pwd)\android-ndk\android-ndk-${{ steps.download-ndk.outputs.version }}"
        [System.Environment]::SetEnvironmentVariable('NDK_HOME', $NDK_HOME, 'User')
        [System.Environment]::SetEnvironmentVariable('PATH', "$NDK_HOME;$Env:PATH", 'User')
        
    - name: Install dependencies
      run: |
        # Install CMake and Ninja using Chocolatey
        choco install cmake ninja -y

    - name: Build the project
      run: |
        # Run your CMake build process
        cmake -S . -B build
        cmake --build build
